name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install Xvfb and set up virtual display
    - name: Install Xvfb and start virtual display
      run: |
        sudo apt-get install xvfb
        Xvfb :99 -screen 0 1024x768x16 &
        echo "Display: $DISPLAY"
      env:
        DISPLAY: ":99"

    # Run the Python script within the virtual display environment
    - name: Test game run
      run: |
        python main.py
      env:
        DISPLAY: ":99"
